---
- name: Check Ansible Environment
  hosts: localhost
  tasks:
    - name: Checking Ansible Version
      ansible.builtin.assert:
        that:
          - "{{ ansible_version.full is defined }}"
          - "{{ ansible_version.full is version('2.9', 'gt') }}"
          - "{{ ansible_os_family == 'Debian' }}"

# Not sure why this is done on localhost every time...
    # - name: Update System Package Cache
    #   apt:
    #     update_cache: yes
    #     cache_valid_time: 3600
    #     force_apt_get: yes
    #   tags: update_system
    #
    # - name: Upgrade System Packages
    #   apt:
    #     upgrade: full
    #     force_apt_get: yes
    #   tags: update_system
    #
    # - name: Remove useless packages from the cache
    #   apt:
    #     autoclean: yes
    #
    # - name: Remove dependencies that are no longer required
    #   apt:
    #     autoremove: yes


# Common Configuration

- name: Apply common configuration to all nodes
  hosts: all
  become: true
  roles:
    - role: common
    # TODO: These is specific to Gnome.
    # - role: user_customizations
    #   tags:
    #     - user_customizations

# Bastions Configuration
- name: Bastion configuration
  hosts: bastions
  become: true
  roles:
    - role: bastion

# Database Server Configuration
- name: Database server configuration
  hosts: database
  become: true
  roles:
    - role: database
      tags:
        - database

# Web Server Configuration
- name: Web server configuration
  hosts: web
  become: true
  roles:
    - role: web/common
      tags:
        - web

# Workstation Configuration
- name: Workstation configuration
  hosts: workstations
  become: true
  roles:
    - role: workstation
      tags:
        - workstation