---
- name: Check Ansible Environment
  hosts: localhost
  tasks:
    - name: Checking Ansible Version
      ansible.builtin.assert:
        that:
          - "{{ ansible_version.full is defined }}"
          - "{{ ansible_version.full is version('2.9', 'gt') }}"
          - "{{ ansible_os_family == 'Debian' }}"

# Common Configuration

- name: Apply common configuration to all nodes
  hosts: all
  become: true
  roles:
    - role: common
    # TODO: These is specific to Gnome.
    # - role: user_customizations
    #   tags:
    #     - user_customizations

# Workstation Configuration
- name: Workstation configuration
  hosts: workstations
  become: true
  roles:
    - role: workstation
      tags:
        - workstation
