---
- name: Check Ansible Environment
  hosts: localhost
  tasks:
    - name: Checking Ansible Version
      assert:
        that:
          - "{{ ansible_version is defined }}"
          - "{{ ansible_version|version_compare(2.7, '>=') }}"

# Common Configuration
- name: apply common configuration to all nodes
  hosts: all
  become: yes
  roles:
    - health
    - common
    - { role: monitoring, tags: monitoring }

# Bastions Configuration
- name: bastion configuration
  hosts: bastions
  become: yes
  roles:
    - bastion

# Database Server Configuration
- name: database server configuration
  hosts: database
  become: yes
  roles:
    - { role: database, tags: ['database'] }

# PXE Server Configuration
- name: pxe server configuration
  hosts: pxe
  become: yes
  roles:
    - { role: pxe, tags: ['pxe'] }

# Web Server Configuration
- name: web server configuration
  hosts: web
  become: yes
  roles:
    - { role: web/common, tags: ['web'] }
    - tools/composer

# Workstation Configuration
- name: workstation configuration
  hosts: workstations
  become: yes
  roles:
    - workstation
    - tools/composer

# ZNC Bouncer
- name: znc bouncer configuration
  hosts: znc
  become: yes
  roles:
    - znc

