---
# Common Configuration
- name: apply common configuration to all nodes
  hosts: all
  sudo: yes
  roles:
    - common
    - health
    - ANXS.fail2ban

# Bastions Configuration
- name: bastion configuration
  hosts: bastions
  sudo: yes
  roles:
    - bastion

# Web Server Configuration
- name: web server configuration
  hosts: web
  sudo: yes
  roles:
    - web/common
    - tools/composer

# Workstation Configuration
- name: workstation configuration
  hosts: workstations
  sudo: yes
  roles:
    - workstation
    - tools/composer

