---
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: yes

- name: Reload php-fpm
  ansible.builtin.service:
    name: php7.2-fpm
    state: reloaded
  become: yes
