---
- name: Ensure packages are installed
  pacman:
    pkg: "{{ item }}"
    state: present
  with_items:
  - bind-tools
  - cryptsetup
  - gimp
  - hexchat
  - mangler
  - php
  - php-mcrypt
  - rsnapshot
  - seahorse
  - shutter
  - terminator
  - thunderbird
  - variety
  - virt-manager
  tags: package

# Install AUR packages
#  - vagrant
#  - spotify
#  - google-chrome-stable
