---
- name: Ensure packages are installed
  ansible.builtin.apt:
    package: "{{ packages }}"
    state: present
  vars:
    packages:
      - gimp
      - terminator

- name: Install Google Software
  ansible.builtin.include_tasks:
    file: software/google.yml
    apply:
      tags:
        - google

- name: Install Yubico Software
  ansible.builtin.include_tasks:
    file: software/yubico.yml
    apply:
      tags:
        - yubico

- name: Install Signal
  ansible.builtin.include_tasks:
    file: software/signal.yml
    apply:
      tags:
        - signal
