---
- name: Ensure packages are installed
  ansible.builtin.apt:
    package: "{{ packages }}"
    state: present
  vars:
    packages:
      - gimp
      - terminator
      - rpi-imager

- name: Install Yubico Software
  ansible.builtin.include_tasks:
    file: software/yubico.yml
    apply:
      tags:
        - yubico

- name: Install Signal
  ansible.builtin.include_tasks:
    file: software/signal.yml
    apply:
      tags:
        - signal

- name: Install flatpak packages
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - com.spotify.Client
      - md.obsidian.Obsidian
      - org.mozilla.firefox
      - org.telegram.desktop
      - com.visualstudio.code
