---
- name: Ensure packages are installed
  ansible.builtin.apt:
    package: "{{ packages }}"
    state: present
  vars:
    packages:
      - curl
      - gimp
      - kdeconnect
      - rpi-imager
      - terminator
      - flatpak
      - plasma-discover-backend-flatpak

- name: Install Signal
  ansible.builtin.include_tasks:
    file: software/signal.yml
    apply:
      tags:
        - signal

- name: Install Steam
  ansible.builtin.include_tasks:
    file: software/steam.yml
    apply:
      tags:
        - steam

- name: Add flathub as remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages
  community.general.flatpak:
    name:
      - com.bitwarden.desktop
      - com.discordapp.Discord
      - com.spotify.Client
      - md.obsidian.Obsidian
      - org.mozilla.firefox
      - org.remmina.Remmina
      - org.telegram.desktop
      - com.visualstudio.code
      - com.yubico.yubioath #The ppa version stopped working.
  notify:
    - Refresh KDE application database

- name: Add zfs-load-key@.service
  ansible.builtin.copy:
    src: zfs-load-key@.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: u+rwx,g=rx,o=rx
