---
- name: Ensure packages are installed
  ansible.builtin.apt:
    package: "{{ packages }}"
    state: present
  vars:
    packages:
      - curl
      - gimp
      - kdeconnect
      - rpi-imager
      - terminator
      - flatpak
      - plasma-discover-backend-flatpak

- name: Install Signal
  ansible.builtin.include_tasks:
    file: software/signal.yml
    apply:
      tags:
        - signal

- name: Install Steam
  ansible.builtin.include_tasks:
    file: software/steam.yml
    apply:
      tags:
        - steam

- name: Install Yubico Software
  ansible.builtin.include_tasks:
    file: software/yubico.yml
    apply:
      tags:
        - yubico

- name: Add flathub as remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - com.spotify.Client
      - md.obsidian.Obsidian
      - org.mozilla.firefox
      - org.telegram.desktop
      - com.visualstudio.code
