---
- name: Load workstation package names for the host OS
  ansible.builtin.include_vars:
    file: "{{ 'Debian' if ansible_facts['os_family'] == 'Debian' else ansible_facts['distribution'] }}.yml"
  tags: always

- name: Ensure workstation packages are installed
  ansible.builtin.package:
    name: "{{ workstation_packages }}"
    state: present

- name: Add flathub as remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install KDE Connect
  ansible.builtin.include_tasks:
    file: software/kdeconnect.yml
    apply:
      tags:
        - kdeconnect

- name: Install Steam
  ansible.builtin.include_tasks:
    file: software/steam.yml
    apply:
      tags:
        - steam

- name: Install GH CLI
  ansible.builtin.include_tasks:
    file: software/gh.yml
    apply:
      tags:
        - gh

- name: Check for KDE Frameworks 6 application cache tool
  ansible.builtin.stat:
    path: /usr/bin/kbuildsycoca6
  register: workstation_kbuildsycoca6

- name: Check for KDE Frameworks 5 application cache tool
  ansible.builtin.stat:
    path: /usr/bin/kbuildsycoca5
  register: workstation_kbuildsycoca5

- name: Ensure a KDE application cache tool is installed
  ansible.builtin.assert:
    that: workstation_kbuildsycoca6.stat.exists or workstation_kbuildsycoca5.stat.exists
    fail_msg: "Neither kbuildsycoca6 nor kbuildsycoca5 is installed."

- name: Install flatpak packages
  community.general.flatpak:
    name:
      - com.bitwarden.desktop
      - com.discordapp.Discord
      - com.spotify.Client
      - com.visualstudio.code
      - com.yubico.yubioath # The ppa version stopped working.
      - md.obsidian.Obsidian
      - org.remmina.Remmina
      - org.signal.Signal
      - org.telegram.desktop
  notify:
    - Refresh KDE application database
