---
- name: Ensure packages are installed
  apt:
    package: "{{ packages }}"
    state: present
  vars:
    packages:
    - cryptsetup
    - gimp
    - rsnapshot
    - terminator
    - ubuntu-restricted-extras
    - virt-manager

- name: Ensure snaps are installed
  snap:
    state: present
    classic: no
    name:
      - bitwarden
      - discord
      - spotify
      - telegram-desktop

- name: Ensure snaps are installed (--classic)
  snap:
    state: present
    classic: yes
    name:
      - atom

- name: Install Google Software
  include_tasks:
    file: software/google.yml
    apply:
      tags:
        - google

- name: Install Yubico Software
  include_tasks:
    file: software/yubico.yml
    apply:
      tags:
        - yubico

- name: Install Signal
  include_tasks:
    file: software/signal.yml
    apply:
      tags:
        - signal
