---
- name: Ensure packages are installed
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
  - mariadb-server
  - python-mysqldb

- name: Enable remote connections
  lineinfile: dest=/etc/mysql/mariadb.conf.d/50-server.cnf regexp="^bind-address" state=absent
  notify: Reload MySQL

- name: Remove anonymous users
  mysql_user: name='' host=localhost state=absent
