---
- name: Ensure packages are installed
  ansible.builtin.apt:
    packages: "{{ packages }}"
    state: present
  vars:
    packages:
    - mariadb-server
    - python-mysqldb

- name: Enable remote connections
  ansible.builtin.lineinfile:
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: "^bind-address"
    state: absent
  notify: Reload MySQL

- name: Remove anonymous users
  community.mysql.mysql_user:
    name: ''
    host: localhost
    state: absent
