---
docker_conflicting_packages:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-engine
  - docker-engine-selinux
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-selinux

docker_prerequisite_packages:
  - dnf-plugins-core

docker_packages:
  - containerd.io
  - docker-buildx-plugin
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
