---
- name: "Setting netdata src"
  set_fact:
    netdata_src: "/usr/src/netdata.git"

- name: Ensure packages are installed
  apt:
    package: "{{ packages }}"
    state: present
  vars:
    packages:
    - zlib1g-dev
    - uuid-dev
    - libmnl-dev
    - gcc
    - make
    - git
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - pkg-config
    - curl
  when: ansible_os_family == 'Debian'

- name: Ensure packages are installed
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - zlib-devel
    - libuuid-devel
    - libmnl-devel
    - gcc
    - make
    - git
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - pkgconfig
    - curl
    - findutils
  when: ansible_os_family == 'RedHat'

#git clone https://github.com/firehol/netdata.git --depth=1
- name: Clone the netdata repo
  git:
    repo: https://github.com/firehol/netdata.git
    depth: 1
    dest: "{{ netdata_src }}"
    version: "{{ netdata.version | default('HEAD') }}"

- name: Install Netdata
  command: ./netdata-installer.sh --dont-wait --auto-update chdir="{{ netdata_src }}" creates=/usr/sbin/netdata

- name: Enable Registry mode
  ini_file:
    path: /etc/netdata/netdata.conf
    backup: yes
    section: registry
    option: enabled
    value: "yes"
  when: netdata_registry_registry_to_announce is defined and ansible_fqdn == netdata_registry_registry_to_announce
  notify: Reload netdata

- name: Disable Registry mode
  ini_file:
    path: /etc/netdata/netdata.conf
    backup: yes
    section: registry
    option: enabled
    value: "no"
  when: netdata_registry_registry_to_announce is defined and ansible_fqdn != netdata_registry_registry_to_announce
  notify: Reload netdata

- name: Set Registry
  ini_file:
    path: /etc/netdata/netdata.conf
    backup: yes
    section: registry
    option: registry to announce
    value: "http://{{ netdata_registry_registry_to_announce }}:{{ netdata_registry_port | default('19999') }}"
  when: netdata_registry_registry_to_announce is defined
  notify: Reload netdata

- name: Enable Slack Alerts
  lineinfile:
    path: /etc/netdata/health_alarm_notify.conf
    state: present
    regexp: "^SEND_SLACK="
    line: "SEND_SLACK=YES"
  when: slack_webhook_url is defined

- name: Set Slack Webhook URL
  lineinfile:
    path: /etc/netdata/health_alarm_notify.conf
    state: present
    regexp: "^SLACK_WEBHOOK_URL="
    line: "SLACK_WEBHOOK_URL={{ slack_webhook_url }}"
  when: slack_webhook_url is defined

- name: Set Slack Channel
  lineinfile:
    path: /etc/netdata/health_alarm_notify.conf
    state: present
    regexp: "^DEFAULT_RECIPIENT_SLACK="
    line: "DEFAULT_RECIPIENT_SLACK={{ slack_alarms|default('infrastructure') }}"
  when: slack_webhook_url is defined
