---
- name: Ensure kdeconnect is installed
  ansible.builtin.apt:
    package: kdeconnect
    state: present

- name: Allow KDE Connect protocols from trusted networks
  community.general.ufw:
    rule: allow
    port: "1714:1764"
    proto: "{{ item.1 }}"
    src: "{{ item.0 }}"
    comment: "KDE Connect {{ item.1 | upper }}"
  with_nested:
    - ["10.24.0.0/24", "100.64.0.0/10"]
    - ["tcp", "udp"]

- name: Reload UFW
  community.general.ufw:
    state: reloaded
