---
# # NOTE: These instructions only work for 64 bit Debian-based
# # Linux distributions such as Ubuntu, Mint etc.
#
# # 1. Install our official public software signing key
# wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg
# cat signal-desktop-keyring.gpg | sudo tee -a /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null
#
# # 2. Add our repository to your list of repositories
# echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' |\
#   sudo tee -a /etc/apt/sources.list.d/signal-xenial.list
#
# # 3. Update your package database and install signal
# sudo apt update && sudo apt install signal-desktop

- name: Add Signal key
  ansible.builtin.get_url:
    url: https://updates.signal.org/desktop/apt/keys.asc
    dest: /etc/apt/keyrings/signal.asc
    mode: '0644'
    force: true

- name: Add Signal repo
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/signal.asc] https://updates.signal.org/desktop/apt xenial main'
    filename: signal-xenial
    state: present
    update_cache: true

- name: Install Signal
  ansible.builtin.apt:
    package: signal-desktop
    state: present
