---
- name: Ensure packages are installed
  apt:
    package: "{{ packages }}"
    state: present
  vars:
    packages:
    - curl
    - php-cli
    - php-curl
  tags: composer

- name: Download Composer and verify checksum
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    checksum: "sha384:{{ lookup('url', 'https://composer.github.io/installer.sig') }}"
  tags: composer

- name: Install composer
  command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer creates=/usr/local/bin/composer
  tags: composer
