---
- name: Ensure packages are installed
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
  - curl
  - php5-cli
  - php5-curl
  - php5-mcrypt
  when: ansible_os_family == 'Debian'
  tags: composer

- name: Ensure packages are installed
  pacman: pkg={{item}} state=latest update_cache=yes
  with_items:
  - curl
  - php
  - php-mcrypt
  when: ansible_os_family == 'Archlinux'
  tags: composer

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer creates=/usr/local/bin/composer
  tags: composer

- name: Make composer executable
  file: path=/usr/local/bin/composer state=file mode="u=rwx,g=rx,o=rx"
  tags: composer
