---
#
- name: Update home directory file permissions
  file: owner="{{item.username}}" path="/home/{{item.username}}" group="{{item.username}}" state="directory"
  with_items: users
  when: users_create_homedirs and users_create_homedirs
