---
- name: Update home directory file permissions
  when: users_create_homedirs and users_create_homedirs
  ansible.builtin.file:
    owner: "{{ item.username }}"
    path: "/home/{{ item.username }}"
    group: "{{ item.username }}"
    state: "directory"
    mode: "0700"
  with_items: "{{ users }}"
  tags: user-management
