---
# Handler to handle common notifications. Handlers are called by other plays.
# See http://ansible.cc/docs/playbooks.html for more information about handlers.

- name: refresh motd
  command: "run-parts /etc/update-motd.d/ > /etc/motd"
