---
- name: refresh motd
  ansible.builtin.shell: run-parts --lsbsysinit /etc/update-motd.d > /var/run/motd.dynamic

- name: restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted
