---
- name: Refresh motd
  ansible.builtin.shell: run-parts --lsbsysinit /etc/update-motd.d > /var/run/motd.dynamic
  register: refresh_motd
  changed_when: refresh_motd.rc != 0

- name: Restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted
