---
- name: Refresh motd
  ansible.builtin.shell: run-parts --lsbsysinit /etc/update-motd.d > /var/run/motd.dynamic
  register: common_refresh_motd
  changed_when: common_refresh_motd.rc != 0

- name: Restart sshd
  ansible.builtin.service:
    name: "{{ common_ssh_service }}"
    state: restarted
