---
- name: Apt for Lets Encrypt
  ansible.builtin.apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present
    update_cache: true

- name: Ensure packages are installed
  ansible.builtin.apt:
    package: "{{ packages }}"
    state: present
  vars:
    packages:
      - nginx
      - php-fpm
      - python-mysqldb
      - python-certbot-nginx
      - ruby-full
      - build-essential
      - zlib1g-dev

- name: Update System Wide Gems
  ansible.builtin.command: gem update --system
  changed_when: false

- name: Create nginx root directory
  ansible.builtin.file:
    path: /srv/nginx
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Disable default virtual host
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Setup systemwide pages
  ansible.builtin.include_tasks: system.yml

- name: Create Deploy Key Location
  ansible.builtin.file:
    path: /etc/ssh/deploy_keys
    state: directory
    mode: "0700"
    owner: root
    group: root

- name: Setup each team
  ansible.builtin.include_tasks: team.yml
  # system_teams needs to be first so that it can be overridden by teams (user defined)
  with_items: "{{ system_teams + teams | default([]) }}"
