---
- name: Ensure packages are installed
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
  - nginx  

- name: Create nginx root directory
  file: path=/srv/nginx state=directory mode=0755 owner=www-data group=www-data

- name: Create SSL storage directory
  file: path=/etc/nginx/ssl state=directory mode="u=rwX,g=rX,o-rwx" owner=root group=root

- name: Clone System
  git: repo=https://github.com/binarypenguin/system.git dest=/srv/nginx/system

- name: Create Sites
  template:
   src: site.j2
   dest: "{{nginx_dir}}/sites-available/{{item.value.name}}"
  with_dict: nginx_sites

- name: Create Virtual Directories
  file:
    path: "{{nginx_www_dir}}/{{item.server.name}}"
    state: directory
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0755
  with_items: nginx_sites

