---
- name: Apt Add Lets Encrypt
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present
    update_cache: yes

- name: Ensure packages are installed
  apt:
    package: "{{ packages }}"
    state: present
  vars:
    packages:
    - nginx
    - php-fpm
    - php7.0-simplexml
    - jekyll
    - python-mysqldb
    - mariadb-client
    - python-certbot-nginx

- name: Create nginx root directory
  file:
    path: /srv/nginx
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Disable default virtual host
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Setup systemwide pages
  include_tasks: system.yml

- name: Setup each team
  include_tasks: team.yml
  with_items: "{{ teams | default([]) + system_teams }}"
  when: teams is defined or system_teams is defined
