---
- name: Set team facts
  ansible.builtin.set_fact:
    team: "{{ item }}"
    sites: "{{ item.sites }}"

- name: Create Team Group
  ansible.builtin.group:
    name: "www-{{ team.name }}"
    system: true
    state: present

- name: Create Team System Account
  ansible.builtin.user:
    name: "www-{{ team.name }}"
    group: "www-{{ team.name }}"
    system: true
    append: true
    home: "{{ nginx_www_dir }}/{{ team.name }}"
    shell: /bin/bash
    state: present

- name: Create new php-fpm pool for team
  ansible.builtin.template:
    src: templates/www.conf.j2
    dest: /etc/php/7.2/fpm/pool.d/www-{{ team.name }}.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload php-fpm

- name: Debug Sites Var
  ansible.builtin.debug:
    var: sites

- name: Create sites
  ansible.builtin.include_tasks: site.yml
  with_items: "{{ sites }}"
  loop_control:
    loop_var: site

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
