
- name: Set team facts
  set_fact:
    team: "{{ item }}"
    sites: "{{ item.sites }}"

- name: Create Team Group
  group:
    name: "www-{{team.name}}"
    system: yes
    state: present

- name: Create Team System Account
  user:
    name: "www-{{team.name}}"
    group: "www-{{team.name}}"
    system: yes
    append: yes
    home: "{{nginx_www_dir}}/{{team.name}}"
    state: present

- name: Create new php-fpm pool for team
  template:
    src: ../files/www.conf.j2
    dest: /etc/php/7.0/fpm/pool.d/www-{{team.name}}.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload php-fpm

- name: Create site virtual directory
  file:
    path: "{{nginx_www_dir}}/{{team.name}}/{{item.domainname}}"
    state: directory
    owner: "www-{{team.name}}"
    group: "www-{{team.name}}"
    mode: 0755
  with_items: "{{ sites }}"

- name: Create available virtual hosts
  template:
    src: ../files/vhost.j2
    dest: "/etc/nginx/sites-available/{{team.name}}-{{item.domainname}}"
    owner: root
    group: root
    mode: 0644
    force: "{{ item.managed|default(True) }}"
  with_items: "{{ sites }}"

- name: Enable virtual hosts
  file:
    src: "/etc/nginx/sites-available/{{team.name}}-{{item.domainname}}"
    dest: "/etc/nginx/sites-enabled/{{team.name}}-{{item.domainname}}"
    owner: root
    group: root
    mode: 0644
    state: link
  with_items: "{{ sites }}"

- name: Pull website repos
  git:
    repo: "{{ item.repo }}"
    dest: "{{nginx_www_dir}}/{{team.name}}/{{item.domainname}}"
  when: item.repo is defined
  with_items: "{{ sites }}"

- name: Compile the Jekylls
  shell: jekyll build
  args:
    chdir: "{{nginx_www_dir}}/{{team.name}}/{{item.domainname}}"
  when: item.type == "jekyll"
  with_items: "{{ sites }}"

- name: Reload nginx
  service: name=nginx state=reloaded
