- name: Set team facts
  set_fact:
    team: "{{ item }}"
    sites: "{{ item.sites }}"

- name: Create Team Group
  group:
    name: "www-{{ team.name }}"
    system: yes
    state: present

- name: Create Team System Account
  user:
    name: "www-{{ team.name }}"
    group: "www-{{ team.name }}"
    system: yes
    append: yes
    home: "{{ nginx_www_dir }}/{{ team.name }}"
    shell: /bin/bash
    state: present

- name: Create new php-fpm pool for team
  template:
    src: templates/www.conf.j2
    dest: /etc/php/7.2/fpm/pool.d/www-{{ team.name }}.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload php-fpm

- name: Create sites
  include_tasks: site.yml
  with_items: "{{ sites }}"
  loop_control:
    loop_var: site

- name: Reload nginx
  service: name=nginx state=reloaded
