---
- name: Ensure packages are installed
  pacman:
    package: "{{ item }}"
    state: present
  with_items:
  - cowsay
  - figlet
  - fortune-mod
  - git
  - htop
  - iftop
  - iotop
  - mtr
  - ncdu
  - nfs-utils
  - openssh
  - python-pip
  - rpcbind
  - screen
  - sshfs
  - tree
  - uptimed
  tags: package

#- name: Install AUR packages
#  - molly-guard

- name: Ensure packages are installed (On physical machines only)
  pacman:
    package: "{{ item }}"
    state: present
  with_items:
  - smartmontools
  #- memtester
  when: ansible_virtualization_role == "host"
  tags: package

##
# MOTD
##
- name: Add ASCII art banner to MOTD
  lineinfile:
    line: "echo -e \e[0;32m$(figlet $(hostname))\e[0m"
    state: present
    path: /etc/motd
  tags: motd
