---
##
# Update System
##
- name: Update System Package Cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
    force_apt_get: yes
  tags: update_system

- name: Upgrade System Packages
  apt:
    upgrade: full
    force_apt_get: yes
  tags: update_system

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

##
# Install Packages
##
- name: Ensure packages are installed
  apt:
    package: "{{ packages }}"
    state: present
  vars:
    packages:
    - cowsay
    - figlet
    - fortune
    - git
    - htop
    - iftop
    - iotop
    - molly-guard
    - mtr
    - ncdu
    - nfs-common
    - python-dev
    - python-pip
    - rpcbind
    - screen
    - ssh
    - sshfs
    - uptimed
  tags: package

- name: Ensure packages are installed (On physical machines only)
  apt:
    package: "{{ packages }}"
    state: present
  vars:
    packages:
      - smartmontools
      - memtester
  when: ansible_virtualization_role == "host"
  tags: package

##
# MOTD
##
- name: Remove help text from MOTD
  file:
    path: /etc/update-motd.d/10-help-text
    state: absent
  notify:
    - refresh motd
  tags: motd

- name: Add ASCII art banner to MOTD
  copy:
    src: 01-banner
    dest: /etc/update-motd.d
    owner: root
    group: root
    mode: u+rwx,g=rx,o=rx
  notify:
    - refresh motd
  tags: motd

##
# Preferences
##
- name: Enable Colored Prompts
  lineinfile:
    dest: /etc/profile.d/binarypenguin.sh
    line: "export force_color_prompt=yes"
    mode: "0755"
    create: yes
  tags: binary-penguin-preferences
