---
- name: Ensure packages are installed
  dnf:
    pkg: "{{ item }}"
    state: present
  with_items:
  - cowsay
  - figlet
  - fortune-mod
  - git
  - htop
  - iftop
  - iotop
  - mtr
  - ncdu
  - nfs-utils
  - openssh
  - python-pip
  - python-devel
  - python2-psutil
  - rpcbind
  - screen
  - fuse-sshfs
  - tree
  - uptimed
  - gcc
  tags: package

- name: Ensure packages are installed (On physical machines only)
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
  - smartmontools
  - memtester
  when: ansible_virtualization_role == "host"
  tags: package

##
# MOTD
##
- name: Add ASCII art banner to MOTD
  lineinfile:
    line: "\e[0;32m$(figlet $(hostname))\e[0m"
    state: present
    path: /etc/motd
  tags: motd
