---
# OS Family Check
- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: package

- include: arch.yml
  when: ansible_os_family == 'Archlinux'
  tags: package

- include: fedora.yml
  when: ansible_os_family == 'RedHat'
  tags: package

# Update PIP
- pip: name=pip state=latest
  tags: pip

# Install setuptools python package.
- pip: name=setuptools state=latest
  tags: pip

# Install thefuck python package.
- pip: name=thefuck state=latest
  tags: thefuck

# Creates file for aliasing fuck to thefuck
- name: Add fuck as alias to thefuck in /etc/profile.d/thefuck.sh
  lineinfile: dest=/etc/profile.d/thefuck.sh line="alias fuck='eval $(thefuck $(fc -ln -1)); history -r'" mode="0755" create=yes
  tags: thefuck

##
# NFS Share
##
- include: nfs.yml
  when: nfsroot is defined and internal_domain is defined
  tags: nfs

##
# SSH Hardening
##
- name: Deploy SSH Config
  template: src=../files/sshd_config.j2
      dest=/etc/ssh/sshd_config
      backup=yes
      owner=0 group=0 mode=0644
      validate='/usr/sbin/sshd -T -f %s'
  notify:
    - restart sshd

##
# Binary Penguin Scripts
##
- name: Clone Binary Penguin Scripts
  git:
      repo: 'https://github.com/binarypenguin/scripts.git'
      dest: /opt/binarypenguin
      update: yes
      accept_hostkey: true
  tags: binary-penguin-scripts

- name: Add Binary Penguin Scripts to $PATH
  lineinfile: dest=/etc/profile.d/binarypenguin.sh line="export PATH=$PATH:/opt/binarypenguin/bin" mode="0755" create=yes
  tags: binary-penguin-scripts
