---
# OS Family Check
- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'
  tags: package

- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'
  tags: package

- include_tasks: fedora.yml
  when: ansible_os_family == 'RedHat'
  tags: package

- name: Install PIP Packages
  pip:
    name:
    - pip
    - setuptools
    - thefuck
    state: present
  tags: pip

# Creates file for aliasing fuck to thefuck
- name: Add fuck as alias to thefuck in /etc/profile.d/thefuck.sh
  lineinfile:
    dest: /etc/profile.d/thefuck.sh
    line: "alias fuck='eval $(thefuck $(fc -ln -1)); history -r'"
    mode: 0755
    create: yes
  tags: thefuck

##
# NFS Share
##
- include_tasks: nfs.yml
  when: nfsroot is defined and internal_domain is defined
  tags: nfs

##
# SSH Hardening
##
- name: Deploy SSH Config
  template:
    src: ../files/sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    owner: root
    group: root
    mode: 0644
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
    - restart sshd

##
# Binary Penguin Scripts
##
- name: Clone Binary Penguin Scripts
  git:
    repo: 'https://github.com/binarypenguin/scripts.git'
    dest: /opt/binarypenguin
    update: yes
    accept_hostkey: true
    version: "{{ binarypenguin_scripts.version | default('HEAD') }}"
  tags: binary-penguin-scripts

- name: Add Binary Penguin Scripts to $PATH
  lineinfile:
    dest: /etc/profile.d/binarypenguin.sh
    line: "export PATH=$PATH:/opt/binarypenguin/bin"
    mode: "0755"
    create: yes
  tags: binary-penguin-scripts
