---
# OS Family Check
- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: package

- include: arch.yml
  when: ansible_os_family == 'Archlinux'
  tags: package

##
# bashrc
##
- name: Find .bashrc files
  find: paths="/home,/etc/skel" patterns=".bashrc" recurse=yes hidden=True
  register: bashrc_dir
  tags: update-bashrc

- name: Update .bashrc to force colored prompts
  lineinfile: dest={{ item.path }} state=present regexp="^#?force_color_prompt" line="force_color_prompt=yes"
  with_items: bashrc_dir.files
  when: bashrc_dir.matched > 0
  tags: update-bashrc

# Install thefuck python package.
- pip: name=thefuck
  tags: update-bashrc

# Alias fuck to thefuck
- name: Add fuck as alias to thefuck in .bashrc
  lineinfile: dest={{ item.path }} line="alias fuck='eval $(thefuck $(fc -ln -1)); history -r'"
  with_items: bashrc_dir.files
  when: bashrc_dir.matched > 0
  tags: update-bashrc

##
# NFS Share
##
- include: nfs.yml
  when: nfsroot is defined and internal_domain is defined
  tags: nfs

##
# Binary Penguin Scripts
##
- name: Clone Binary Penguin Scripts
  git:
      repo: 'https://github.com/binarypenguin/scripts.git'
      dest: /opt/binarypenguin
      update: yes
      accept_hostkey: true

- name: Add Binary Penguin Scripts to $PATH
  lineinfile: dest=/etc/profile.d/binarypenguin.sh line="export PATH=$PATH:/opt/binarypenguin/bin" mode="0755" create=yes
