---
- name: Ensure packages are installed
  ansible.builtin.apt:
    package: "{{ packages }}"
    state: present
  vars:
    packages:
      - figlet
      - git
      - htop
      - iftop
      - iperf
      - iotop
      - molly-guard
      - mtr
      - ncdu
      - python3-dev
      - python3-pip
      - screen
      - ssh
      - sshfs
      - uptimed
  tags: package

- name: Create /etc/apt/keyrings folder
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Ensure packages are installed (On physical machines only)
  ansible.builtin.apt:
    package: "{{ packages }}"
    state: present
  vars:
    packages:
      - smartmontools
      - memtester
  when: ansible_virtualization_role == "host"
  tags: package

# TODO: These need moved to be installed at the user level
# - name: Install PIP3 Packages
#   ansible.builtin.pip:
#     name:
#     - setuptools
#     - thefuck
#     executable: /usr/bin/pip3
#     state: present
#   tags: pip3
#
# Creates file for aliasing fuck to thefuck
# - name: Add fuck as alias to thefuck in /etc/profile.d/thefuck.sh
#   ansible.builtin.lineinfile:
#     dest: /etc/profile.d/thefuck.sh
#     line: "alias fuck='eval $(thefuck $(fc -ln -1)); history -r'"
#     mode: 0755
#     create: yes
#   tags: thefuck

##
# Preferences
##
- name: Include MOTD Task
  ansible.builtin.include_tasks: motd.yml

- name: Enable Colored Prompts
  ansible.builtin.lineinfile:
    dest: /etc/profile.d/binarypenguin.sh
    line: "export force_color_prompt=yes"
    mode: "0755"
    create: true
  tags: binary-penguin-preferences

##
# NFS Share
##
# TODO: We aren't currently using NFS Shares
# - include_tasks: nfs.yml
#   when: nfsroot is defined and internal_domain is defined
#   tags: nfs

##
# SSH Hardening
##
- name: Disable password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication '
    insertafter: '^#PasswordAuthentication '
    line: 'PasswordAuthentication no'
    validate: /usr/sbin/sshd -t -f %s
    state: present
  notify:
    - restart sshd

##
# Binary Penguin Scripts
##
- name: Clone Binary Penguin Scripts
  ansible.builtin.git:
    repo: 'https://github.com/binarypenguin/scripts.git'
    dest: /opt/binarypenguin
    update: true
    accept_hostkey: true
    version: "{{ binarypenguin_scripts.version | default('HEAD') }}"
  tags: binary-penguin-scripts

- name: Add Binary Penguin Scripts to $PATH
  ansible.builtin.lineinfile:
    dest: /etc/profile.d/binarypenguin.sh
    line: "export PATH=$PATH:/opt/binarypenguin/bin"
    mode: "0755"
    create: true
  tags: binary-penguin-scripts
