---
- name: Create mount point for NFS server
  file: path=/net state=directory
  when: ansible_domain == "{{ internal_domain }}"


- name: Mount NFS share
  mount: name=/net src={{ nfsroot }} fstype=nfs4 opts=_netdev,auto state=mounted
  when: ansible_domain == "{{ internal_domain }}"
