---
- name: Create mount point for NFS server
  ansible.builtin.file: path=/net state=directory
  when: ansible_domain == internal_domain
  tags: nfs

- name: Mount NFS share
  ansible.posix.mount: name=/net src={{ nfsroot }} fstype=nfs4 opts=_netdev,auto state=mounted
  when: ansible_domain == internal_domain
  tags: nfs
