---
# ufw supports connection rate limiting, which is useful for protecting
# against brute-force login attacks. ufw will deny connections if an IP
# address has attempted to initiate 6 or more connections in the last
# 30 seconds. See  http://www.debian-administration.org/articles/187
# for details. Typical usage is:
- name: Limit SSH Access
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
  tags:
    - ufw

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
    logging: true
  tags:
    - ufw
