---

- name: Install ZNC
  apt_repository:
    repo: 'ppa:teward/znc'
    state: present
    update_cache: yes

- name: Install ZNC
  apt:
    package: "{{ packages }}"
    state: present
  vars:
    packages:
    - znc
    - znc-dbg
    - znc-dev
    - znc-perl
    - znc-python
    - znc-tcl

- name: Create ZNC User
  user:
    name: znc
    comment: "ZNC Bouncer"
    createhome: yes
    home: /opt/znc
    system: yes

- name: Create ZNC Service
  copy:
    src: znc.service
    dest: /etc/systemd/system/znc.service
    owner: root
    group: root
    mode: 0644

